# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs:
  python: circleci/python@2.1.1
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  pylint:
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: "pylint"
          command: pylint common lettings profiles
  build:
#    docker:
#      - image: cimg/python:3.10.13
    executor:
      name: python/default
      tag: "3.10"
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run:
          name: "pre-commit"
          command: pre-commit run --all
      - run:
          name: "tests"
          command: pytest
      - run:
          name: "coverage"
          command: coverage run -m pytest

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
#      - python/test:
#          args: '--dev'
#          pkg-manager: pip
#          test-tool: pytest
      - pylint
